# .github/workflows/build-macos.yml
name: Build Electrum on macOS (x86)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # Use macOS 11 (Intel) to match build docs.
    # The runner provides macOS ~11.7.9 and Xcode 13.2.1.
    runs-on: macos-11

    steps:
      # Step 1: Check out repository to match the docs' structure
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          # This creates a path like /Users/runner/work/project/electrum
          path: electrum
          submodules: 'recursive'

      # Step 2: Set up Xcode to match docs' requirements
      - name: Select Xcode 13.2.1 and verify
        run: |
          sudo xcode-select -s /Applications/Xcode_13.2.1.app/Contents/Developer
          echo "--- Verifying Xcode version ---"
          xcodebuild -version
          echo "--- Verifying Clang version ---"
          gcc --version

      # Step 3: Update Homebrew
      - name: Update Homebrew
        run: brew update

      # Step 4: Clean up stale files and run the build
      - name: Build Electrum
        # Run all build-related commands from inside the checked-out directory
        working-directory: ./electrum
        run: |
          # This cleanup step is the most direct fix for your specific error
          echo "Cleaning up stale build directories..."
          rm -rf dist/ build/

          # Run the main build script
          echo "Starting the build..."
          ./contrib/osx/make_osx.sh
        timeout-minutes: 45

      # Step 5: Upload the build artifact
      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Electrum-macOS-unsigned
          path: electrum/dist/electrum-*-unsigned.dmg
