# .github/workflows/build-macos.yml
name: Build Electrum on macOS (x86)

on:
  push:
    branches: [ "4.6.0" ]
  pull_request:
    branches: [ "4.6.0" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # Use an Intel (x86_64) runner. macos-13 is an Intel runner.
    # For more details, see: https://github.com/actions/runner-images
    runs-on: macos-13

    steps:
      # Step 1: Check out the repository code
      - name: Check out repository
        uses: actions/checkout@v4
        # The build script uses submodules, so we need to fetch them
        with:
          submodules: 'recursive'

      # Step 2: Set up Homebrew
      # The runner environment usually has Homebrew pre-installed.
      # This step ensures it's available and updates it.
      - name: Set up Homebrew
        id: setup-brew
        run: |
          echo "Homebrew is expected to be pre-installed on this runner."
          brew --version
          brew update

      # Step 3: Run the main build script
      # This script handles all dependencies and the final compilation.
      - name: Build Electrum
        run: ./contrib/osx/make_osx.sh
        # Add a timeout in case the build gets stuck
        timeout-minutes: 45

      # Step 4: Upload the build artifact
      # This makes the final .dmg file available for download from the workflow run page.
      - name: Upload DMG Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Electrum-macOS-unsigned
          # The build script places the output in the 'dist' directory.
          # We use a wildcard to match the generated DMG file regardless of version.
          path: dist/electrum-*-unsigned.dmg
